export const owlTips: readonly string[] = [
  // Original 20
  "Hoot hoot! Break big tasks into smaller ones — it's easier to eat an elephant one bite at a time.",
  "Hoo! Take a break every 25 minutes. Your brain will thank you. (Look up the Pomodoro Technique!)",
  "Hoot! Why do programmers prefer dark mode? Because light attracts bugs.",
  "Hoooot! Limit your work in progress. Finishing one thing beats half-finishing three.",
  "Hoo hoo! A clean board is a happy board. Archive cards you're done with!",
  "Hoot hoot hoot! There are only two hard things in computer science: cache invalidation, naming things, and off-by-one errors.",
  "Hooo! Move cards left to right, not in circles. If a card keeps bouncing back, it needs a conversation.",
  "Hoot! If it's not on the board, it doesn't exist. Capture everything!",
  "Hoo hoo hoo! A SQL query walks into a bar, sees two tables, and asks: 'Can I JOIN you?'",
  "Hoot hoot! Review your board at the start of each day. Five minutes of planning saves an hour of chaos.",
  "Hoooo! The best code is no code at all. The second best is code someone else maintains.",
  "Hoot! Blocked? Flag it immediately. Don't let it sit and pretend it'll fix itself.",
  "Hoo! Why was the JavaScript developer sad? Because he didn't Node how to Express himself.",
  "Hoot hoot! Celebrate when cards reach Done. Small wins fuel big momentum.",
  "Hoo hoo! It works on my machine! Then we'll ship your machine.",
  "Hooot! Don't multitask. Context switching costs more than you think — about 20 minutes per switch.",
  "Hoot! How many programmers does it take to change a light bulb? None, that's a hardware problem.",
  "Hoo hoot! Keep card titles short and actionable. 'Fix login bug' beats 'There's this thing with the login that's weird'.",
  "Hoooo! The best time to refactor was yesterday. The second best time is today.",
  "Hoot hoo! Owl always be here if you need productivity advice!",

  // Owl jokes
  "Hoo hoo! What do you call an owl who does magic tricks? Hoo-dini!",
  "Hoot! What's an owl's favorite subject? Owlgebra!",
  "Hooo! Why don't owls study for tests? They'd rather wing it.",
  "Hoot hoot! What do you call an owl dressed in armor? A knight owl!",
  "Hoo! Did you hear about the owl who lost his voice? He didn't give a hoot.",
  "Hoooot! What's an owl's favorite type of music? Owl-ternative rock.",
  "Hoot! Knock knock. Who's there? Owl. Owl who? Owl be seeing you later!",
  "Hoo hoo hoo! What do owls say on Halloween? Happy Owl-oween!",
  "Hoot hoot! Why do owls make great detectives? They're always watching whooo-dunit.",
  "Hooo! What's an owl's favorite drink? Hoot beer!",
  "Hoot! What do you call a baby owl swimming? A moist-owlette.",
  "Hoo hoot! Why did the owl invite friends over? He didn't want to be owl by himself.",

  // Programming jokes
  "Hoot hoot! Why do Java developers wear glasses? Because they can't C#.",
  "Hoo! A programmer's wife says: 'Go to the store and get a loaf of bread. If they have eggs, get a dozen.' He comes home with 12 loaves.",
  "Hoooo! What's a programmer's favorite hangout place? Foo Bar.",
  "Hoot! !false — it's funny because it's true.",
  "Hoo hoo! There are 10 types of people in the world: those who understand binary, and those who don't.",
  "Hooot! Why did the developer go broke? Because he used up all his cache.",
  "Hoot hoot! What did the CSS say to the HTML? You've got no style.",
  "Hoo! A QA engineer walks into a bar. Orders 1 beer. Orders 0 beers. Orders 99999 beers. Orders -1 beers. Orders a lizard.",
  "Hoot! Why do programmers always mix up Christmas and Halloween? Because Oct 31 == Dec 25.",
  "Hoo hoo hoo! git commit -m 'fixed the bug' — narrator: he did not fix the bug.",
  "Hoooot! What's a pirate's favorite programming language? You'd think R, but their first love is the C.",
  "Hoot hoot! The best thing about a boolean is even if you're wrong, you're only off by a bit.",
  "Hooo! Why did the functions stop calling each other? Because they got too many arguments.",

  // Kanban jokes & tips
  "Hoot! What did one kanban column say to the other? Stop pushing my cards!",
  "Hoo hoo! My kanban board is a lot like my fridge — I keep adding things and nothing ever leaves.",
  "Hoot hoot! A card in 'In Progress' for three weeks isn't in progress. It's in denial.",
  "Hoooo! Why did the card break up with the kanban board? It felt too boxed in.",
  "Hoo! The 'Done' column called. It misses you. Move some cards over!",
  "Hoot! My kanban board has three columns: To Do, Doing, and Who Am I Kidding.",
  "Hoo hoot! A kanban board walks into a standup. Everyone asks: 'Any blockers?' The board screams.",
  "Hoot hoot hoot! If your 'In Progress' column is wider than your 'Done' column, we need to talk.",

  // Productivity tips
  "Hoot! Eat the frog first — tackle your hardest task at the start of the day when your energy is highest.",
  "Hoo hoo! The two-minute rule: if a task takes less than two minutes, do it now instead of adding it to the board.",
  "Hoooo! Batch similar tasks together. Your brain thanks you for not context-switching between wildly different work.",
  "Hoot hoot! Write tomorrow's to-do list before you leave today. Future you will be grateful.",
  "Hooo! Say no more often. Every yes is a no to something else on your board.",
  "Hoo! Time-box your work. An open-ended task expands to fill all available time.",
  "Hoot! Done is better than perfect. Ship it and iterate.",
  "Hoot hoot! Take a walk when you're stuck. Solutions love to appear when you stop staring at the screen.",
  "Hoo hoo hoo! Keep meetings short. If it could be an async update, skip the meeting.",
  "Hoooot! Track your wins, not just your to-dos. You've accomplished more than you think.",
  "Hoot! Focus on outcomes, not hours. Nobody cares if you worked 10 hours on something that didn't matter.",
  "Hoo hoot! Set a WIP limit and stick to it. Three things in progress is plenty.",
  "Hoot hoot! Automate the boring stuff. If you do it more than twice, script it.",
  "Hooo! End your day by reviewing what you accomplished. It builds momentum for tomorrow.",
  "Hoo! Your brain can only hold about four things in working memory. Write the rest down!",
  "Hoot hoot hoot! Protect your deep work time. Block off your calendar and guard it fiercely.",
  "Hoooo! Small consistent progress beats heroic bursts. Show up every day.",
  "Hoot! If everything is a priority, nothing is. Pick your top three for today.",

  // Feature discovery tips
  "Hoot! Did you know? Switch to Calendar view to see all your cards with due dates on a monthly grid!",
  "Hoo hoo! Try clicking a card on the calendar — it opens the full detail modal right from there.",
  "Hoot hoot! Set due dates on your cards and they'll show up in the Calendar view. Owl-ganized!",
  "Hooo! The List view now shows due dates instead of descriptions. Great for scanning what's coming up!",
  "Hoo! Click any row in the List view to open the card detail modal. Quick and easy!",
  "Hoot! Want a cleaner header? Turn on Compact Header in Settings > Appearance to hide button labels.",
  "Hoo hoo! Three ways to view your board: Board, List, and Calendar. Try them all!",
  "Hoot hoot! Add checklists to your cards — just click '+ Add checklist item' below the description.",
  "Hooo! Check off items right from the board card — no need to open the detail modal!",
  "Hoo! Your checklist progress shows as a little bar on each card. Satisfying to watch it fill up!",
  "Hoot! Set a default card type in Settings > Card Types so new cards are automatically categorized.",
  "Hoo hoo! Use Ctrl+Z to undo and Ctrl+Shift+Z to redo. Owl mistakes are reversible!",
  "Hoot hoot! Check out Analytics to see your cycle time and throughput. Data-driven owls ship faster!",
  "Hooo! Deleted cards aren't gone forever — they go to the Archive where you can restore them anytime.",
  "Hoo! Export your board from Settings > Data to back it up or share it. Import it anywhere!",
  "Hoot! Use the search bar to fuzzy-find cards by title. Matching cards get highlighted on the board.",
  "Hoo hoo! Cards you archive still count in your analytics history. Your past work isn't forgotten!",
  "Hoot! Press ⌘K to open the command palette — jump to any action without touching the mouse. Owl-efficient!",
];

export const nightOwlTips: readonly string[] = [
  "*yaaawn* Hoot... You know what's a great feature? Sleep.",
  "Hoo... *rubs eyes* Bugs written after midnight take twice as long to fix in the morning.",
  "*yaaawn* Hoooot... Your code will still be here tomorrow. Your energy won't.",
  "Hoo hoo... *blinks slowly* Save your work and close the laptop. Trust me.",
  "*yaaawn* Hoot hoot... Even owls need rest. And I'm literally an owl.",
  "Hoo... *stretches wings* The best debugging tool at this hour is a pillow.",
  "*yaaawn* Hoooo... Late-night commits are just future reverts waiting to happen.",
  "Hoot... *nods off* ...huh? Oh. You're still here? Go to bed!",
  "Hoo hoo... *droopy eyes* Fun fact: sleep deprivation has the same effect as being legally drunk. Ship responsibly.",
  "*yaaawn* Hoot... The kanban board will be right where you left it. Promise.",
  "Hoo... *yawns widely* Every hour of sleep you skip now costs two hours of productivity tomorrow.",
  "*yaaawn* Hoooot... You wouldn't deploy on a Friday. Don't code at 2 AM either.",
  "Hoo hoo... *rubs eyes* Your future self is begging you to step away from the keyboard.",
  "*yaaawn* Hoot hoot... There's a reason they call it 'dream code' — because you should be dreaming right now.",
  "Hoo... *barely awake* I'd give you a productivity tip, but at this hour, the only tip is: sleep.",
  "*yaaawn* Hoooo... Did you know? Owls are nocturnal. You are not. Go to bed.",
  "Hoot... *heavy eyelids* One more commit? No. One more pillow.",
  "Hoo hoo... *yawns* The longest-lived bugs are the ones born between midnight and 4 AM.",
  "*yaaawn* Hoot... You're burning the midnight owl. Please stop.",
  "Hoo... *stretches* I'm a night owl and even I think you should call it a night.",
  "*yaaawn* Hoooot... Your code isn't going anywhere. But your REM cycles are.",
  "Hoo hoo... *blinks* What do you call a developer who codes past midnight? An owl-cohollic.",
  "*yaaawn* Hoot hoot... Sleep is just offline mode for humans. Time to shut down.",
  "Hoo... *droopy eyes* The only branch you should be on right now is the one you're sleeping on.",
  "*yaaawn* Hooo... You've been staring at this screen owl night long. Enough!",
  "Hoot... *yawns* What do tired programmers and owls have in common? They both make questionable decisions in the dark.",
  "Hoo hoo... *nods off* Your kanban board has a hidden column you're ignoring: 'Go To Sleep'.",
  "*yaaawn* Hoot... I'd tell you an owl pun but it's too late. Get it? Too. Late.",
  "Hooo... *rubs eyes* Even your commit messages are getting sleepy. 'asdffix thing' is not a message.",
  "*yaaawn* Hoo hoo... You're not a night owl. You're a night human pretending. Go roost.",
  "Hoot... *barely conscious* The board will still be here tomorrow. You might not be if you don't sleep.",
  "*yaaawn* Hoooot... What's an exhausted developer's favorite design pattern? The Singleton... bed.",
];
